### ISSUE TITLE
Missing release models.

### ISSUE THREAD

**Issue by trevor403** [Lornatang/ESRGAN-PyTorch#1]
It seems as though the models to be downloaded by `download_weights.py` are not in the project releases. Note `ESRGAN_PSNR_X4.pth` is available elsewhere online but I can't seem to find a copy of `ESRGAN_RRDB_X4.pth` anywhere. 

Would you be able to publish those releases?

Thank you!

**Comment by Lornatang** [comment]
soon.....

**Comment by Lornatang** [comment]
@trevor403 ...

**Comment by Lornatang** [comment]
It upload.
