### ISSUE TITLE
When I train the Discriminator, I meet a issue about cuda

### ISSUE THREAD

**Issue by YS-16** [Lornatang/ESRGAN-PyTorch#11]
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling cublasCreate(handle)

**Comment by cyun-404** [comment]
me too!!ㅠ@ㅜ
![image](https://user-images.githubusercontent.com/73474866/149480011-353326b2-996b-4b37-99d7-85a4398d81b5.png)

**Comment by YS-16** [comment]
I change the loss function "nn.BCELoss" to ""nn.BCEWithLogitsLoss", and I solve this issue.
