### ISSUE TITLE
Why the volatile gpu util is low(less than 20%)

### ISSUE THREAD

**Issue by ChandlerHarden** [Lornatang/ESRGAN-PyTorch#12]
Hello, I train your program on my laptop with 2080ti but it turns out that during training the volatile GPU util is low(5% - 18%). But your SRGAN-PyTorch model can get nearly 100% volatile GPU util.  I wonder why the ESRGAN-PyTorch model has such low GPU util?

**Comment by Lornatang** [comment]
Because the ESRGAN code is still being updated~~~~

**Comment by ChandlerHarden** [comment]
> Because the ESRGAN code is still being updated~~~~

Thanks for replying.  Is that mean the model itself is completed and can be used as ESRGAN baseline and being updated doesn't modify the structure of the model?

**Comment by Lornatang** [comment]
Yes, the old model is available, the new model will be updated later, and the old and new models are compatible

**Comment by ChandlerHarden** [comment]
> 

Thanks. Wish u good luck
