### ISSUE TITLE
In valid, I should change the color range??

### ISSUE THREAD

**Issue by cyun-404** [Lornatang/ESRGAN-PyTorch#13]
![image](https://user-images.githubusercontent.com/73474866/151500516-2f3f13ad-a001-42b9-84c7-3cbae568471d.png)

when I search about this, In "skimage\color\colorconv.py" want the RGB 3 value But I got 4 value..
How can I run the validation.py file????

**Comment by Lornatang** [comment]
RGB channel not RGBA channel
