### ISSUE TITLE
What config should I edit if I want to valid other datasets like urban100 or ost300?

### ISSUE THREAD

**Issue by ChandlerHarden** [Lornatang/ESRGAN-PyTorch#16]
Hello. If I want to validate other datasets whose image size is not like DIV2K, Which config should I edit?

**Comment by Lornatang** [comment]
This requires you to make it like the Set5 dataset by yourself

**Comment by ChandlerHarden** [comment]
Does it mean that I cannot use your model and weigh test other datasets?

**Comment by Lornatang** [comment]
You can test the library model weights on any image, but the premise is that you must process datasets such as OST300 into a directory similar to the Set5 test dataset
