### ISSUE TITLE
Dataset download link are canceled.

### ISSUE THREAD

**Issue by AshJordanZhao** [Lornatang/ESRGAN-PyTorch#18]
Hello! Could u please re-upload ur dataset in the /data/readme? Both google and baidu drive are unavaliable.

**Comment by Lornatang** [comment]
Ok, Wait...

**Comment by Lornatang** [comment]
Updated dataset download link.

**Comment by AshJordanZhao** [comment]
> Updated dataset download link.

ty for ur timely response!

**Comment by Lornatang** [comment]
@AshJordanZhao The broken link has been fixed, do you have time to take a look?

**Comment by AshJordanZhao** [comment]
> @AshJordanZhao The broken link has been fixed, do you have time to take a look?

yeah ive check the data already. maybe it is better if u write the default image size(like 128x128, scale x4) in readme XD

**Comment by AshJordanZhao** [comment]
> Thank you for your suggestion, it is currently defined in the configuration file.

XD ty for ur nice code btw
谢谢兄弟 咱还是讲中文舒服点233

**Comment by Lornatang** [comment]
我没太多时间去同时维护五个项目，每个项目的写法基本上都比较简单
