### ISSUE TITLE
About release model

### ISSUE THREAD

**Issue by yamiefun** [Lornatang/ESRGAN-PyTorch#2]
Hi

Could you release a pretrained model of this repo?
You've mention ESRGAN_X4.pth in README but i just can't find it.
I'm just curious about the performance of ESRGAN, and I'm going to retrain the model with my project's dataset.
Thanks very much!

**Comment by Lornatang** [comment]
Soon...

**Comment by Lornatang** [comment]
@yamiefun It upload.
