### ISSUE TITLE
resume训练模型时不太对劲

### ISSUE THREAD

**Issue by Wakie01** [Lornatang/ESRGAN-PyTorch#20]
大佬，我发觉我resume模型继续训练时，虽然resume成功了，但继续训练时的精度显示，好像重新训练的那样

**Comment by Lornatang** [comment]
代码是最新的么，最近有一次代码层面更新。
具体表现在什么地方，是Loss还是？PSNR？

**Comment by Wakie01** [comment]
具体表现在PSNR
我先更新试一下
谢啦谢啦，这么晚还回复我的问题，真的是thank you so much

**Comment by Lornatang** [comment]
你看下resume是否完全，保证优化器参数也加载正常了

**Comment by Wakie01** [comment]
你好，在加载优化器参数时报错了：
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group
我现在注释了：
d_optimizer.load_state_dict(checkpoint["optimizer"])
g_optimizer.load_state_dict(checkpoint["optimizer"])
然后跑通了，但不知道这样对训练会不会有影响
我的环境是：
python3.8
cuda11.3
pytorch1.10.0

**Comment by Wakie01** [comment]
确实，这样resume后，没有效果，相当于重新训练，可是为什么在加载优化器参数时会报错呢😫😫

**Comment by Lornatang** [comment]
这个错误在最新版提交中已经修复了，你看下
