### ISSUE TITLE
Keep ratio input image not upscale

### ISSUE THREAD

**Issue by phamkhactu** [Lornatang/ESRGAN-PyTorch#21]
Thank for your great repo! I have question : "how can I keep original ratio image (height, weight) after infer, not upscale bigger 4 times.
If can, Can you share how to config it?
Many thanks

**Comment by Lornatang** [comment]
You can implement your idea with the following code.
Modify `model.py` 193~198 line

```python
# original code
out = torch.add(out1, out2)

out = self.upsampling1(F.interpolate(out, scale_factor=2, mode="nearest"))
out = self.upsampling2(F.interpolate(out, scale_factor=2, mode="nearest"))

out = self.conv3(out)
# new code
out = torch.add(out1, out2)

# out = self.upsampling1(F.interpolate(out, scale_factor=2, mode="nearest"))
# out = self.upsampling2(F.interpolate(out, scale_factor=2, mode="nearest"))

out = self.conv3(out)
```
Wish help you~

**Comment by phamkhactu** [comment]
@Lornatang Many thanks. I comment out as you recommended, but the output not good, I test with your image `figure/baboon_lr.png`.
Maybe when comment out, image not supper resolution.?

**Comment by Lornatang** [comment]
The model is trained on X4, it is definitely not possible to use X1 directly, you have to retrain your X1 model

**Comment by phamkhactu** [comment]
@Lornatang many thanks.
