### ISSUE TITLE
请问是否尝试在ESRGAN上用更大的缩放倍数？比如X8？ X16？

### ISSUE THREAD

**Issue by jingoudan** [Lornatang/ESRGAN-PyTorch#26]
Hi，大佬您好！
我尝试用ESRGAN做8倍缩放的超分辨，我用了Generator model中三次 upsampling layer来放大8倍 以及 换成pixelshuffle的上采样方式，这两种情况下训练出来的图像质量都很差，我设置的HR_size是256的大小，LR_size则对应32，请问是否是LR太小，upscale_factor太大 导致超分结果不好？还是说RRDBNet的结构设计就不太适合太大缩放倍率的超分任务？

**Comment by Lornatang** [comment]
据我所知， 线性堆叠的上采样层在4X下表现效果比较好，通常X8会使用其它形式的上采样层；
LR_size越大效果通常会越好，这些尺度变化在相关论文中已得到证明，但也需要考虑到实际硬件资源需求，根据经验判断，32，48，64都是一个不错的选择。

**Comment by jingoudan** [comment]
> 

好的，感谢解答！！谢谢~

**Comment by Lornatang** [comment]
这个问题是一个拓展性问题，可以尝试，效果等同于其他X8，X16模型。
