### ISSUE TITLE
相对GAN的损失函数

### ISSUE THREAD

**Issue by jingoudan** [Lornatang/ESRGAN-PyTorch#27]
Hi，大佬您好！
在train_esrgan.py文件中 对抗损失函数这个地方的设置我不太明白。
代码里 更新D网络时 和 更新G网络时的对抗损失 是一样的。
我的理解是更新D时，
对于HR：d_hr_loss = adversarial_criterion( Dra(xr,xf) , real_label)
对于SR ：d_sr_loss = adversarial_criterion( Dra(xf,xr) , fake_label)
更新G时，
对于HR：d_hr_loss = adversarial_criterion( Dra(xr,xf) , fake_label)
对于SR ：d_sr_loss = adversarial_criterion( Dra(xf,xr) , real_label)
这样才和论文中写的判别器损失和生成器损失公式对应上了,
请问是我对相对判别器的损失理解有误还是代码里笔误了？

**Comment by Lornatang** [comment]
谢谢你的指出，最近一次更新给写错了~~~,已修复

**Comment by jingoudan** [comment]
> 谢谢你的指出，最近一次更新给写错了~~~,已修复

好嘞！感谢感谢~
