### ISSUE TITLE
Question about pretrained model

### ISSUE THREAD

**Issue by wlmqjiyizh** [Lornatang/ESRGAN-PyTorch#3]
Hi, Mr. Liu.
thanks for your concise code! As a beginner, I learned a lot from reading your code.

Now I got a question about pretrained model. I **can not** download pre-trained model from link ["https://github.com/Lornatang/ESRGAN-PyTorch/releases/download/0.1.0/ESRGAN16_DF2K-a03a643d.pth"](url) when I execute "python test_benchmark.py -a esrgan16 --pretrained --gpu 0 data" in the command line. I try to open the link in Chrome browser and also got "404 not found".
I think maybe something wrong with the pre-trained model link, or my way of getting model is not right.
 
I am looking forward to your reply. You can contact me jyz3119305750@stu.xjtu.edu.cn. 
Thanks again.

**Comment by Lornatang** [comment]
Link fixed.
