### ISSUE TITLE
Version Requirements not specified in Readme.

### ISSUE THREAD

**Issue by hiren-2911** [Lornatang/ESRGAN-PyTorch#30]
Hey!
Can you please list the version requirements of python, PyTorch, and torchvision?
I am not able to run the code because I am getting an error in importing torchvision.transforms and torchvision.models.
I am currently running the code on below mentioned versions:
pytorch==1.11.0 torchvision==0.12.0 torchaudio==0.11.0 cudatoolkit=11.3

**Comment by Lornatang** [comment]
Torch=1.12.0
