### ISSUE TITLE
Inquiries on AMP

### ISSUE THREAD

**Issue by 2minkyulee** [Lornatang/ESRGAN-PyTorch#33]
Hello Lornatang.

Thanks for your great work.
I'm very impressed with the simple/straightforward yet efficient re-implementation of published works.

To the best of my knowledge, a slight performance decrease can occur when training generative models with mixed precision.
Although this research was based on unconditional generative models, I do believe that it can stand equal to conditional generative models as SR networks.

Thus, I was wondering if there are any ablations on the performance with and without AMP. (Either RRDB or ESRGAN will help)
Also, I'm curious about how much faster the training is with and without AMP.

Thank you in advance.

**Comment by Lornatang** [comment]
Sorry， I see you email. 

1. Python style MATLAB bicubic downsample function，antialiasing=True
2. GTmod12 To be fair, keep GT consistent. Of course, GTmod2, GTmod3, GTmod4 the result will be better
