### ISSUE TITLE
[Errno 2] No such file or directory: './weights/GAN.pth'

### ISSUE THREAD

**Issue by OpencvW** [Lornatang/ESRGAN-PyTorch#4]
Hi，it shows this error‘’No such file or directory: './weights/GAN.pth‘’ when i run the testing code? how do i download GAN.pth file?

**Comment by Lornatang** [comment]
The exact path should be './weights/Generator.pth`.
Change according to the real path。

**Comment by Lornatang** [comment]
Or use `--pretrained`. Then will download weights from this repo.

**Comment by OpencvW** [comment]
Thanks for your reply. 
”python3 test_image.py -a esrgan16 --lr ./test   --pretrained --gpu 0” this is command line. i think i already seleted the pretrained model, but i got same error. And there is no Generator.pth file in weights folder.

**Comment by OpencvW** [comment]
@Lornatang Thank you alot! Problem was solved.
