### ISSUE TITLE
PSNR

### ISSUE THREAD

**Issue by ajj998ajj** [Lornatang/ESRGAN-PyTorch#7]
What is the final PSNR of this model?

My operation uses the esrgan23 model.，the default value is used for training epoch, but the final PSNR trained is less than 20. What's the matter?

**Comment by Suanmd** [comment]
> What is the final PSNR of this model?
> 
> My operation uses the esrgan23 model.，the default value is used for training epoch, but the final PSNR trained is less than 20. What's the matter?

Same results, did you solve it?

**Comment by Lornatang** [comment]
PSNR cal function have bug, I will fix.
