### ISSUE TITLE
如何加载本地图片

### ISSUE THREAD

**Issue by SolitaryManF** [Lornatang/ESRGAN-PyTorch#9]
你好，我想问一下如何使用本地图片数据库进行训练？

**Comment by Lornatang** [comment]
Is the problem solved?

**Comment by SolitaryManF** [comment]
> 

我看错啦，以为你用的是在线的不用下载的数据，原来你也是先把DIV2K数据下载到data文件夹下面的，我先自己试一下，谢谢你

**Comment by Lornatang** [comment]
好的

**Comment by SolitaryManF** [comment]
> 好的![图片](https://user-images.githubusercontent.com/90755894/145743684-8fe11ec6-d517-46ce-aa9f-66e34a78ac85.png)
你好，我在运行train.py 的时候，报错了一个文件夹地址的错误，这个DFO2K是如何产生的，我的data文件夹目录是否命名错了？盼复，谢谢。

**Comment by SolitaryManF** [comment]
> > 好的![图片](https://user-images.githubusercontent.com/90755894/145743684-8fe11ec6-d517-46ce-aa9f-66e34a78ac85.png)
> > 你好，我在运行train.py 的时候，报错了一个文件夹地址的错误，这个DFO2K是如何产生的，我的data文件夹目录是否命名错了？盼复，谢谢。
另外：我是在windows上面运行的

**Comment by Lornatang** [comment]
DFO2K实际上是DIV2K+OST+Flick2K的组合，大概有一万多张图像，你可以再代码里修改输入图像文件夹为DIV2K

**Comment by SolitaryManF** [comment]
> DFO2K实际上是DIV2K+OST+Flick2K的组合，大概有一万多张图像，你可以再代码里修改输入图像文件夹为DIV2K

![图片](https://user-images.githubusercontent.com/90755894/145749086-6e689af4-ce93-44b9-a4c7-8d36ab2ac581.png)
这2个int行参数image_size和upscale_factor不是需要设置的嘛？我这边没有设置就能直接运行train了

**Comment by Lornatang** [comment]
按照原始论文是不需要设置的。
